captcha:
    height: 80
    width: 240
    length: 6
    max_skew: 0.7
    dot_count: 80
email:
    host: smtp.qq.com
    port: 465
    from: 2652777599@qq.com
    nickname: Xiaoyu_Wang
    secret: aynjkwnibmwxdiei
    is_ssl: true
es:
    url: http://127.0.0.1:9200
    username: ""
    password: ""
    is_console_print: true
gaode:
    enable: true
    key: 43fc67c95a6390a4e0452be53c9914b2
jwt:
    access_token_secret: VMtA6emVlecNbWq69pB-lY8UZIMZh8WTUZHfEDmxYjA=
    refresh_token_secret: VIrbM3JdDS4KobT9ZpBekBlqU0JSq3vzz6jpsevwOns=
    access_token_expiry_time: 2h
    refresh_token_expiry_time: 7d
    issuer: go_blog
mysql:
    host: 127.0.0.1
    port: 3306
    config: charset=utf8mb4&parseTime=True&loc=Local
    db_name: blog_db
    username: root
    password: root
    max_idle_conns: 10
    max_open_conns: 100
    log_mode: info
qiniu:
    zone: z0
    bucket: wwyblog112
    img_path: https://image.xxx.xxx/
    access_key: BcaKxra1vgy28Y4CHJYPKzEoO_j7zZwc7T58pUci
    secret_key: vmb-YFdCmFqXf6Jjlzu9EJWcJCshOsMTsAylhp1u
    use_https: true
    use_cdn_domains: true
qq:
    enable: true
    app_id: "000000000"
    app_key: xxxxxxxxxxxxxxxx
    redirect_uri: http://www.wwyBlog.cn/login?flag=qq
redis:
    address: 127.0.0.1:6379
    password: ""
    db: 0
system:
    host: 0.0.0.0
    port: 8080
    env: release
    router_prefix: api
    use_multipoint: true
    sessions_secret: YEthzbuwUMpnNvon5_1ugzwh9EDOF6qbKdYkWvl2QWo=
    oss_type: local
upload:
    size: 20
    path: uploads
website:
    logo: /uploads/image/532ff2a146d161818845040556fc1307-20250226101107.png
    full_logo: /uploads/image/532ff2a146d161818845040556fc1307-20250226101117.png
    title: Xiaoyu_Wangのblog
    slogan: Xiaoyu_Wangのblog
    slogan_en: Blog Title
    description: Go语言博客
    version: 1.0.0
    created_at: "2025-1-15"
    icp_filing: icp备案号
    public_security_filing: 公安备案号
    bilibili_url: https://space.bilibili.com/435344704?spm_id_from=333.1007.0.0
    gitee_url: https://gitee.com/wang-wenyu-fdhfj
    github_url: https://github.com/KOIOIO
    name: Xiaoyu_Wang
    job: 工作
    address: 河南省郑州市
    email: 2652777599@qq.com
    qq_image: /uploads/image/34672cbe3812cd56564ed12fa3d67b1e-20250226101740.jpg
    wechat_image: ""
zap:
    level: info
    filename: log/go_blog.log
    max_size: 200
    max_backups: 30
    max_age: 5
    is_console_print: true
